site:
  name: Chronicles of The Business Pathfinder
  site: 'https://business-pathfinder.com'
  base: '/'
  trailingSlash: false
  mirrors:
    ru: 'https://business-pathfinder-chronicles.com'
  googleSiteVerificationId:

socials:
  tiktok: 'https://tiktok.com/@business.pathfinder'
  youtube: 'https://youtube.com/@sjpark_businesspathfinder?si=sxv7iHlT0Pj9_bZW'
  linkedin: 'https://www.linkedin.com/in/sj-park-business-pathfinder?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app'
  facebook: 'https://www.facebook.com/share/1AXtFCqfVA/'
  x: 'https://x.com/SJ_ParkBp?t=AKHpdwx0-ABMVERpyGAtKg&s=09'
  instagram: 'https://www.instagram.com/business.pathfinder.official?igsh=MXM2bnhsb2FuajBjeQ=='

contact:
  emailAddress: 'info@business-pathfinder.com'
  telegramUsername: 'arthelokyo'
  whatsappNumber: '79161234567' # Use international format without '+' sign

donation:
  usdtTrc20Address: 'TNvw1QnD4fDXsPSibv3eFjR113omUwv6b4'
  usdtErc20Address: '0xC7AD3cbFFD37ece5b2f27088F52879eE066Fc5aA'
  usdcSolAddress: '4JjXtZFLkAQj3YTRAUabhPLJuHbnSem4X71HADrbLtqh'

  cryptoPaymentLink: 'https://nowpayments.io/donation/business_pathfinder'
  bankCardPaymentLink: 'https://nowpayments.io/donation/business_pathfinder'

formsUrls:
  consultationFormTestUrl: 'https://n8n.georgeparkdev.com/webhook-test/submit-consultation-request-en'
  consultationFormUrl: 'https://n8n.georgeparkdev.com/webhook/submit-consultation-request-en'
  vacancyFormTestUrl: 'https://n8n.georgeparkdev.com/webhook-test/submit-vacancy-request-en'
  vacancyFormUrl: 'https://n8n.georgeparkdev.com/webhook/submit-vacancy-request-en'

# Default SEO metadata
metadata:
  title:
    default: Chronicles of The Business Pathfinder
    template: '%s â€” Chronicles of The Business Pathfinder'
  description: 'Description of the website.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Chronicles of The Business Pathfinder
    images:
      - url: '~/assets/images/defaultimage.webp'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@SJ_ParkBp'
    site: '@SJ_ParkBp'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: 'blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

  project:
    isEnabled: true
    projectsPerPage: 6

    project:
      isEnabled: true
      permalink: 'project/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'project' # Projects main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedProjectsEnabled: true
    relatedProjectsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: G-RYLPNZ9LNG

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
