site:
  name: Хроники Бизнес-Следопыта
  site: 'https://business-pathfinder-chronicles.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

socials:
  tiktok: 'https://www.tiktok.com/@arthelokyo'
  youtube: 'https://www.youtube.com/@arthelokyo'
  vk: 'https://vk.com/arthelokyo'
  ok: 'https://ok.ru/profile/151932261944'
  facebook: 'https://www.facebook.com/arthelokyo'
  x: 'https://x.com/arthelokyo'
  instagram: 'https://www.instagram.com/arthelokyo/'

contact:
  emailAddress: 'contact@arthelokyo.com'
  telegramUsername: 'arthelokyo'
  whatsappNumber: '79161234567' # Use international format without '+' sign

# Default SEO metadata
metadata:
  title:
    default: Хроники Бизнес-Следопыта
    template: '%s — Хроники Бизнес-Следопыта'
  description: 'Описание Сайта.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Хроники Бизнес-Следопыта
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  language: ru
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: 'blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

  project:
    isEnabled: true
    projectsPerPage: 6

    project:
      isEnabled: true
      permalink: 'project/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'project' # Projects main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedProjectsEnabled: true
    relatedProjectsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
